### ISSUE TITLE
Questions, comments, Etc.

### ISSUE THREAD

**Issue by Wilto** [Wilto/wilto-makes-food#12]
Since I already have forms, and need to figure out a way to manage them alongside static site deployment (#10), I should figure out a way to take questions from readers. The Patreon feed might work for this; maybe I do a “best of…” every so often, and publish the questions and answers as an article?

**Comment by murtaugh** [comment]
IMHO, it would be excellent if each recipe had a GitHub label, and you could submit questions as issues with that label. Unfortunately I don't see a way to automate the creation and assigning of labels, so it's probably more work than it's worth.

How about linking to a Slack channel?

**Comment by Wilto** [comment]
> IMHO, it would be excellent if each recipe had a GitHub label, and you could submit questions as issues with that label.

Ahh, I dig the idea of tying questions to recipes a _lot_. I think I’d want to own the venue, though—figure “sign up for a GitHub account” could put off less tech-y folks. Having it baked into the site could be cool, though; figure a “having trouble with…” or “have questions about this recipe” input baked into each recipe page, y’know? I gotta think this through some.

> How about linking to a Slack channel?

I like it. Maybe a Discord? Patreon asked for one; I wonder if that’s, like, the Thing To Do for this stuff.

**Comment by murtaugh** [comment]
Discord is a nice community chat solution, but Slack seems like a better fit for this particular case, since it allows for deep linking.

**Comment by Wilto** [comment]
Ah-hah, good call.

**Comment by Wilto** [comment]
“Lousy ol’ Twitter,” say the people:
https://twitter.com/WiltoMakesFood/status/993947609692823554

If nothing else, I should call this out as a Thing One Can Do on the website someplace.

**Comment by murtaugh** [comment]
Wow, I'm surprised how poorly the chatrooms did.

**Comment by Wilto** [comment]
Yeah, same here.
