### ISSUE TITLE
Recipe json...

### ISSUE THREAD

**Issue by murtaugh** [Wilto/wilto-makes-food#16]
Did you make up the recipe json format or did you get it from somewhere? I've tried to come up with one for myself, but never came up with the idea of breaking up whole numbers and fractions, which is great.

**Comment by Wilto** [comment]
Made this sucker up. It might be a little _too_… granular, I guess? It was kind of necessary to break up the styling the way I wanted it all, though: https://github.com/Wilto/wilto-makes-food/blob/master/_src/_includes/layouts/recipe.njk#L86

**Comment by murtaugh** [comment]
Yeah, I like it. I was always trying for something not granular enough.

I was trying to optimize for better user input, but there's probably a middle ground. Like, it's probably very possible to allow the user to input "1½" (or 1.5 I guess) into one field, and break that up into multiple json values.

**Comment by alexcarpenter** [comment]
Have you looked into structured data, to get nice looking google search results? https://developers.google.com/search/docs/guides/intro-structured-data

**Comment by Wilto** [comment]
@alexcarpenter I might accidentally be covered there, thanks to Pinterest (#2).

I don’t think I’ve got it 100% right, but I’ve got the recipes all [microdata](https://www.w3.org/TR/microdata/)’d up (Pinterest is flagging me for missing a active time (`itemprop="cookTime"`) and a rating (`itemprop="aggregateRating"`) whiiiich… I guess I’ll just flub? I wasn’t gonna add ratings.

**Comment by alexcarpenter** [comment]
O nice!
