### ISSUE TITLE
Did I do offline right?

### ISSUE THREAD

**Issue by Wilto** [Wilto/wilto-makes-food#5]
Ghost stories about Flying-Dutchman-style Service Workers have me wondering.

**Comment by tevko** [comment]
You don't need to add the serviceWorker to the list of items that should be cached

**Comment by Wilto** [comment]
Oh, huh. Chrome was barking at me about the request failing while offline, so I just kind of assumed; I guess that’s… a little ouroborosian though.

**Comment by Wilto** [comment]
(And thanks!)
