### ISSUE TITLE
Search on a static site

### ISSUE THREAD

**Issue by Wilto** [Wilto/wilto-makes-food#8]
Will this have to be done client-side?

**Comment by Wilto** [comment]
I guess I could run a little server-side dealie that consumes a the-whole-site JSON?

**Comment by Wilto** [comment]
It might not be pretty, but it works.

**Comment by danburzo** [comment]
I just stumbled on your blog and was surprised to see a search function. That's a very neat solution, would not have thought about it! Thanks for the tip :-)
